FROM golang:alpine AS builder
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o srv-user -a -tags netgo -ldflags '-s -w' ./srv-user

FROM busybox
LABEL justin justin@
COPY --from=builder /app/srv-user .
EXPOSE  8888
ENTRYPOINT ["/srv-user"]