FROM golang:alpine AS builder
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -o srv-article -a -tags netgo -ldflags '-s -w' ./srv-article

FROM busybox
LABEL justin justin@
COPY --from=builder /app/srv-article .
EXPOSE  8899
ENTRYPOINT ["/srv-article"]